#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export PATH=${PATH}:/usr/local/mysql/bin

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# homebrew no auto update!
export HOMEBREW_NO_AUTO_UPDATE=1

alias cl="clear"
alias dot="/usr/local/bin/git --git-dir=$HOME/.dotfiles.git/ --work-tree=$HOME"
alias dotadd=". ~/bin/quick_commit"
alias gs="git status"
alias ide="source $HOME/bin/tmx/ide"
alias planckadd="source $HOME/bin/qmk_planck.sh"
alias npml="npm list --depth=0 2>/dev/null"
alias npmg="npm list -g --depth=0 2>/dev/null"
alias picker="npm run --prefix ~/Dropbox/_rpp/flower-picker/ start"
alias src="exec zsh"
alias gd="git diff -- ':!package-lock.json' ':!yarn.lock'"
alias disp="~/Desktop/detect-displays.command"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

[ -f "/Users/aj/.ghcup/env" ] && source "/Users/aj/.ghcup/env" # ghcup-env

###########
# chruby
###########
source /usr/local/opt/chruby/share/chruby/chruby.sh

# To enable auto-switching of Rubies specified by .ruby-version files,
# add the following to ~/.bash_profile or ~/.zshrc:
source /usr/local/opt/chruby/share/chruby/auto.sh

# choose ruby version
chruby ruby-3.2.2

# if trying to install a ruby version older than 3.1.3, 3.0.5, or 2.7.7
# (but not 2.6.x or older), then you’ll need to install Ruby like this:
# ruby-install 3.1.2 -- --enable-shared
# from https://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/#how-to-install-different-versions-of-ruby-and-switch-between-them

# pnpm
export PNPM_HOME="/Users/aj/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

source /Users/aj/.config/broot/launcher/bash/br
